compressionLevel: 0

enableGlobalCache: true

logFilters:
  - code: YN0005
    level: discard
  - code: YN0076
    level: discard

nodeLinker: node-modules

npmRegistryServer: 'https://registry.yarnpkg.com'

plugins:
  - path: ../.yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: ../.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

unsafeHttpWhitelist:
  - localhost

yarnPath: ../.yarn/releases/yarn-4.3.0.cjs
installStatePath: '../.yarn/scripts-install-state.gz'
# Sometimes you get a "The remote archive doesn't match the expected checksum" error, uncommenting this line will fix it
# checksumBehavior: 'update'
