name: Markdown Links Check
# runs every monday at 9 am
on:
  schedule:
    - cron: "0 9 * * 1"

permissions:
  contents: read

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
        # checks all markdown files from important folders including all subfolders
        with:
          # only show errors that occur instead of successful links + errors
          use-quiet-mode: "yes"
          # output full HTTP info for broken links
          use-verbose-mode: "yes"
          config-file: ".github/workflows/markdown-link-check-config.json"
      # Notify to Discord channel on failure
      - name: Send Discord Notification
        if: failure() # Only run this step if previous steps failed
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content":"The Markdown Links Check workflow has failed in the repository: [storybook]"}' ${{ secrets.DISCORD_MONITORING_URL }}
