name: Triage issues

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  issues: write

jobs:
  triage:
    name: Nissuer
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: balazsorban44/nissuer@92ef22afd6a75e5e588f5d689a1fd3433f596f82 # 1.10.0
        with:
          label-comments: |
            {
              "good first issue": ".github/comments/good-first-issue.md"
            }
          reproduction-comment: ".github/comments/invalid-link.md"
          reproduction-hosts: "github.com,codesandbox.io,stackblitz.com"
          reproduction-link-section: "### Reproduction link(.*)### Reproduction steps"
          reproduction-invalid-label: "needs reproduction"
          reproduction-issue-labels: "bug,needs triage"
